runs-on: ubuntu-latest

steps:
  - uses: actions/checkout@v2

  - name: Read .nvmrc
    id: node_version
    run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

  - name: Set Up node
  - uses: actions/checkout@v3
  - uses: pnpm/action-setup@v2
    with:
      version: 6.32.9
  - uses: actions/setup-node@v3
    with:
      node-version: ${{ steps.node_version.outputs.NODE_VERSION }}
      cache: 'pnpm'

  - name: Install dependencies
    run: pnpm install --frozen-lockfile

  - name: Test and Build Codebase
    run: pnpm run ci

  - name: Deploy gh-pages if on master
    if: ${{ github.ref == 'refs/heads/master' }}
    uses: JamesIves/github-pages-deploy-action@4.1.4
    with:
      branch: gh-pages
      folder: build
